IGVF-389-software
IGVF-DACC/igvf-ui pull request #114
Opened 2023-02-22 20:37 UTC by mingjiecn

2023-02-22 22:31 UTC, forresttanaka requested changes
Nice new implementation of the software-version table! I hope the SortableGrid component was easy to figure out how to configure.

2023-02-22 22:31 UTC, forresttanaka commented on components/search/__tests__/list-renderer.test.js
> +    const paths = MeasurementSet.getAccessoryDataPaths([item]);
Change this to `SoftwareVersion.getAccessoryDataPaths([item])` and you’ll get full Jest coverage.

2023-02-23 14:49 UTC, mingjiecn commented on components/software-version-table.js
> +        </Link>
Really helpful! Thank you!

2023-02-23 16:04 UTC, forresttanaka approved these changes
😎

2023-02-24 17:53 UTC, merged