IGVF-805-ui-biomarker-page
IGVF-DACC/igvf-ui pull request #229
Opened 2023-07-19 12:10 UTC by KAndreeva

Added a few property to the biomarker page.

2023-07-19 15:12 UTC, forresttanaka requested changes
🆒 Just a couple spelling corrections.

2023-07-19 15:12 UTC, forresttanaka commented on components/search/list-renderer/biomarker.js
> +  const searchIdentifer = getBiomarkerSearchIdentifier(biomarker);
Change to `searchIdentifier`.

2023-07-20 00:44 UTC, KAndreeva commented on lib/biomarker.js
> +// Set up biomarker search page itentifier for top of item
done

2023-07-20 00:44 UTC, KAndreeva commented on components/search/list-renderer/biomarker.js
> +  const searchIdentifer = getBiomarkerSearchIdentifier(biomarker);
done

2023-07-20 01:23 UTC, forresttanaka approved these changes
👍

2023-07-20 17:31 UTC, merged