Igvf-261-add-button (renamed branch)
IGVF-DACC/igvf-ui pull request #84
Opened 2022-10-17 20:16 UTC by dougli1sqrd

I had to create a new branch name in order to satisfy the demo gods (underscores not allowed in branch names). Since PRs don't know how to track changed branch names, here's a new PR with the same code. Here is the old PR: https://github.com/IGVF-DACC/igvf-ui/pull/82

2022-10-17 21:25 UTC, forresttanaka submitted a review, later dismissed
Odd you have to “run prettier.” It should run itself every time you save your file.

2022-10-17 21:25 UTC, forresttanaka commented on components/add.js
> +};
It’s not required, but you can catch more errors is you select the allowed values with [PropTypes.oneOf](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes)

2022-10-18 19:55 UTC, forresttanaka submitted a review, later dismissed

2022-10-19 17:29 UTC, forresttanaka requested changes
OK, now _I’m_ going to complain about a lack of gaps. There’s no gap between the Add button and the panel on individual schema pages. If you sign in and look at the Pages page, you can see an Add Page button with an `mb-1` gap between it and the panel. Could you add that gap to the schema add button as well? It’s also a different color, but I don’t know if I should make the “Add Page” button primary-outline or if you should make the Add button success-outline. We haven’t decided on button colors and styles overall yet.

2022-10-19 18:52 UTC, dougli1sqrd commented
I had to fiddle a little, but I got it

2022-10-20 15:55 UTC, forresttanaka approved these changes
Thanks. We need to get back to work on the design document so that similar things on different pages appear the same.

2022-10-20 19:00 UTC, merged