SNO2-13-add-opensearch
IGVF-DACC/igvf-ui pull request #89
Opened 2022-11-12 03:36 UTC by keenangraham

2022-11-12 03:38 UTC, keenangraham commented on .circleci/config.yml
> +            - IGVFD_BRANCH: try-deploy-indexer-to-cloud
Remember to revert this before merging.

2022-11-16 21:18 UTC, keenangraham commented
@forresttanaka Any other tests or changes you want to make to this branch before merging?

2022-11-16 23:06 UTC, forresttanaka requested changes
I think that all looks good. Just have to get rid of the console.log I added in user-profile.js.

2022-11-17 00:28 UTC, forresttanaka submitted a review, later dismissed

2022-11-21 18:05 UTC, merged